import type { AllocationConfig } from "./types";

// ---------------------------------------------------------------------------
// Holding-wallet addresses for each ALM (Active Liquidity Manager) entity.
// ---------------------------------------------------------------------------
export const ALM_ADDRESSES: Record<string, string> = {
  spark_ethereum:  "0x1601843c5E9bC251A3272907010AFa41Fa18347E",
  spark_base:      "0x2917956eFF0B5eaF030abDB4EF4296DF775009cA",
  spark_optimism:  "0x876664f0c9Ff24D1aa355Ce9f1680AE1A5bf36fB",
  spark_unichain:  "0x345E368fcCd62266B3f5F37C9a131FD1c39f5869",
  spark_arbitrum:  "0x92afd6F2385a90e44da3a8B60fe36f6cBe1D8709",
  spark_avalanche: "0xecE6B0E8a54c2f44e066fBb9234e7157B15b7FeC",
  grove_ethereum:  "0x491EDFB0B8b608044e227225C715981a30F3A44E",
  grove_avalanche: "0x7107DD8F56642327945294a18A4280C78e153644",
  grove_base:      "0x9B746dBC5269e1DF6e4193Bcb441C0FbBF1CeCEe",
  grove_plume:     "0x1DB91ad50446a671e2231f77e00948E68876F812",
  obex_ethereum:   "0xb6dD7ae22C9922AFEe0642f9Ac13e58633f715A2",
};

// ---------------------------------------------------------------------------
// Allocation list
//
// `underlying` references a token in src/allocationData/tokens.ts by its
// "<blockchain>:<address>" id.  The blockchain for an allocation is always
// determined by its underlying token — there is no separate `blockchain` field.
//
// ---------------------------------------------------------------------------
const allocations: AllocationConfig[] = [
  // -------------------------------------------------------------------------
  // Spark
  // -------------------------------------------------------------------------
  {
    id: "spark-syrup-usdc-ethereum",
    underlying: "ethereum:0x80ac24aa929eaf5013f6436cda2a7ba190f5cc0b",
    name: "Syrup USDC",
    protocol: "maple",
    star: "Spark",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-syrup-usdt-ethereum",
    underlying: "ethereum:0x356b8d89c1e1239cbbb9de4815c39a1474d5ba7d",
    name: "Syrup USDT",
    protocol: "maple",
    star: "Spark",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-paypal-usd-ethereum",
    underlying: "ethereum:0x6c3ea9036406852006290770BEdFcAbA0e23A0e8",
    name: "PayPal USD",
    protocol: "paypal",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark-usdt-ethereum",
    underlying: "ethereum:0xe7dF13b8e3d6740fe17CBE928C7334243d86c92f",
    name: "Spark USDT",
    protocol: "sparklend",
    star: "Spark",
    isLending: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark-dai-ethereum",
    underlying: "ethereum:0x4DEDf26112B3Ec8eC46e7E31EA5e123490B05B8B",
    name: "Spark DAI",
    protocol: "sparklend",
    star: "Spark",
    isLending: true,
    containsIdle: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark-pyusd-ethereum",
    underlying: "ethereum:0x779224df1c756b4EDD899854F32a53E8c2B2ce5d",
    name: "Spark PYUSD",
    protocol: "sparklend",
    star: "Spark",
    isLending: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark-usdc-vault-base",
    name: "Spark USDC Vault",
    protocol: "morpho",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_base,
  },
  {
    id: "spark-spark-usds-ethereum",
    underlying: "ethereum:0xC02aB1A5eaA8d1B114EF786D9bde108cD4364359",
    name: "Spark USDS",
    protocol: "sparklend",
    star: "Spark",
    isLending: true,
    containsIdle: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark.fi-pyusd-reserve-ethereum",
    underlying: "ethereum:0xA632D59b9B804a956BfaA9b48Af3A1b74808FC1f",
    name: "Spark.fi PYUSD Reserve",
    protocol: "curve",
    star: "Spark",
    isLP: true,
    containsIdle: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark-usdc-ethereum",
    underlying: "ethereum:0x377C3bd93f2a2984E1E7bE6A5C22c525eD4A4815",
    name: "Spark USDC",
    protocol: "sparklend",
    star: "Spark",
    isLending: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark-blue-chip-usdc-vault-ethereum",
    name: "Spark Blue Chip USDC Vault",
    protocol: "morpho",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-spark.fi-usdt-reserve-ethereum",
    underlying: "ethereum:0x00836Fe54625BE242BcFA286207795405ca4fD10",
    name: "Spark.fi USDT Reserve",
    protocol: "curve",
    star: "Spark",
    isLP: true,
    containsIdle: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-aave-avalanche-usdc-avalanche",
    underlying: "avalanche:0x625e7708f30ca75bfd92586e17077590c60eb4cd",
    name: "Aave Avalanche USDC",
    protocol: "aave",
    star: "Spark",
    isLending: true,
    holdingWallet: ALM_ADDRESSES.spark_avalanche,
  },
  {
    id: "spark-spark-prime-usdc-1-ethereum",
    underlying: "ethereum:0x38464507E02c983F20428a6E8566693fE9e422a9",
    name: "Spark Prime USDC 1",
    protocol: "arkis",
    star: "Spark",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "spark-anchorage-ethereum",
    underlying: "ethereum:0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    name: "Anchorage",
    protocol: "anchorage",
    star: "Spark",
    module: "anchorage",
    // No holdingWallet — balance is provided by the custom adapter.
  },
  {
    id: "spark-base-psm3-usdc-base",
    name: "base PSM3 USDC",
    protocol: "PSM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_base,
  },
  {
    id: "spark-unichain-psm3-usdc-unichain",
    name: "unichain PSM3 USDC",
    protocol: "PSM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_unichain,
  },
  {
    id: "spark-arbitrum-psm3-usdc-arbitrum",
    name: "arbitrum PSM3 USDC",
    protocol: "PSM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_arbitrum,
  },
  {
    id: "spark-optimism-psm3-usdc-optimism",
    name: "optimism PSM3 USDC",
    protocol: "PSM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_optimism,
  },
  {
    id: "spark-base-alm-usdc-base",
    name: "base ALM USDC",
    protocol: "ALM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_base,
  },
  {
    id: "spark-unichain-alm-usdc-unichain",
    name: "unichain ALM USDC",
    protocol: "ALM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_unichain,
  },
  {
    id: "spark-arbitrum-alm-usdc-arbitrum",
    name: "arbitrum ALM USDC",
    protocol: "ALM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_arbitrum,
  },
  {
    id: "spark-optimism-alm-usdc-optimism",
    name: "optimism ALM USDC",
    protocol: "ALM",
    star: "Spark",
    skip: true,
    holdingWallet: ALM_ADDRESSES.spark_optimism,
  },
  // -------------------------------------------------------------------------
  // Grove
  // -------------------------------------------------------------------------
  {
    id: "grove-janus-henderson-anemoy-aaa-clo-fund-token-avalanche",
    underlying: "avalanche:0x58f93d6b1ef2f44ec379cb975657c132cbed3b6b",
    name: "Janus Henderson Anemoy AAA CLO Fund Token",
    protocol: "centrifuge",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.grove_avalanche,
  },
  {
    id: "grove-janus-henderson-anemoy-aaa-clo-fund-token-ethereum",
    underlying: "ethereum:0x5a0F93D040De44e78F251b03c43be9CF317Dcf64",
    name: "Janus Henderson Anemoy AAA CLO Fund Token",
    protocol: "centrifuge",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-blackrock-usd-institutional-digital-liquidity-fund-ethereum",
    underlying: "ethereum:0x6a9DA2D710BB9B700acde7Cb81F10F1fF8C89041",
    name: "BlackRock USD Institutional Digital Liquidity Fund - I Class",
    protocol: "blackrock",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-janus-henderson-anemoy-treasury-fund-ethereum",
    underlying: "ethereum:0x8c213ee79581Ff4984583C6a801e5263418C4b86",
    name: "Janus Henderson Anemoy Treasury Fund",
    protocol: "centrifuge",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "grove-aave-ethereum-rlusd-ethereum",
    underlying: "ethereum:0xFa82580c16A31D0c1bC632A36F82e83EfEF3Eec0",
    name: "Aave Ethereum RLUSD",
    protocol: "aave",
    star: "Grove",
    isLending: true,
    isMerkle: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-aave-horizon-rwa-rlusd-ethereum",
    underlying: "ethereum:0xE3190143Eb552456F88464662f0c0C4aC67A77eB",
    name: "Aave Horizon RWA RLUSD",
    protocol: "aave",
    star: "Grove",
    isLending: true,
    isMerkle: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "grove-anemoy-tokenized-apollo-diversified-credit-fund-token-plume",
    underlying: "plume:0x9477724Bb54AD5417de8Baff29e59DF3fB4DA74f",
    name: "Anemoy Tokenized Apollo Diversified Credit Fund Token",
    protocol: "centrifuge",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "grove-grove-x-steakhouse-high-yield-ausd-monad",
    underlying: "monad:0x32841A8511D5c2c5b253f45668780B99139e476D",
    name: "Grove x Steakhouse High Yield AUSD",
    protocol: "morpho",
    star: "Grove",
    isYBS: true,
    holdingWallet: "0x94B398ACb2fcE988871218221EA6a4a2b26CcCbC",
  },
  {
    id: "grove-aave-horizon-rwa-usdc-ethereum",
    underlying: "ethereum:0x68215B6533c47ff9f7125aC95adf00fE4a62f79e",
    name: "Aave Horizon RWA USDC",
    protocol: "aave",
    star: "Grove",
    isLending: true,
    isMerkle: true,
    skip: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-usdc-monad",
    underlying: "monad:0x754704Bc059F8C67012fEd69BC8A327a5aafb603",
    name: "USDC",
    protocol: "circle",
    star: "Grove",
    skip: true,
    holdingWallet: "0x94B398ACb2fcE988871218221EA6a4a2b26CcCbC",
  },
  {
    id: "grove-grove-x-steakhouse-ausd-ethereum",
    underlying: "ethereum:0xBEEfF0d672ab7F5018dFB614c93981045D4aA98a",
    name: "Grove x Steakhouse AUSD",
    protocol: "morpho",
    star: "Grove",
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-grove-x-steakhouse-usdc-high-yield-ethereum",
    underlying: "ethereum:0xBeefF08dF54897e7544aB01d0e86f013DA354111",
    name: "Grove x Steakhouse USDC High Yield",
    protocol: "morpho",
    star: "Grove",
    holdingWallet: ALM_ADDRESSES.grove_base,
  },
  {
    id: "grove-grove-x-steakhouse-usdc-ethereum",
    underlying: "ethereum:0xBEEf2B5FD3D94469b7782aeBe6364E6e6FB1B709",
    name: "Grove x Steakhouse USDC",
    protocol: "morpho",
    star: "Grove",
    holdingWallet: ALM_ADDRESSES.grove_base,
  },
  {
    id: "grove-grove-x-steakhouse-usdc-high-yield-base",
    underlying: "base:0xBeEf2d50B428675a1921bC6bBF4bfb9D8cF1461A",
    name: "Grove x Steakhouse USDC High Yield",
    protocol: "morpho",
    star: "Grove",
    holdingWallet: ALM_ADDRESSES.grove_base,
  },
  {
    id: "grove-steakusdc-v2-base",
    underlying: "base:0xbeef0e0834849aCC03f0089F01f4F1Eeb06873C9",
    name: "SteakUSDC V2",
    protocol: "morpho",
    star: "Grove",
    isLending: true,
    skip: true,
    holdingWallet: ALM_ADDRESSES.grove_base,
  },
  {
    id: "grove-securitize-tokenized-aaa-clo-fund-ethereum",
    underlying: "ethereum:0x51C2d74017390CbBd30550179A16A1c28F7210fc",
    name: "Securitize Tokenized AAA CLO Fund",
    protocol: "securitize",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-galaxy-arch-clo-token-avalanche",
    underlying: "avalanche:0x2c0adff8e114f3ca106051144353ac703d24b901",
    name: "Galaxy Arch CLO Token",
    protocol: "inx",
    star: "Grove",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.spark_ethereum,
  },
  {
    id: "grove-curve-lp-ausd-usdc-ethereum",
    underlying: "ethereum:0xe79c1c7e24755574438a26d5e062ad2626c04662",
    name: "Curve LP AUSD/USDC",
    protocol: "curve",
    star: "Grove",
    isLP: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  {
    id: "grove-uniswap-lp-ausd-usdc-ethereum",
    underlying: "ethereum:0xbAFeAd7c60Ea473758ED6c6021505E8BBd7e8E5d",
    name: "Uniswap LP AUSD/USDC",
    protocol: "uniswap",
    star: "Grove",
    isLP: true,
    holdingWallet: ALM_ADDRESSES.grove_ethereum,
  },
  // -------------------------------------------------------------------------
  // Obex
  // -------------------------------------------------------------------------
  {
    id: "obex-syrup-usdc-ethereum",
    underlying: "ethereum:0x80ac24aa929eaf5013f6436cda2a7ba190f5cc0b",
    name: "Syrup USDC",
    protocol: "maple",
    star: "Obex",
    isYBS: true,
    holdingWallet: ALM_ADDRESSES.obex_ethereum,
  },
];

export default allocations;
